FROM python:3.11
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY message.py /code/app/main.py
WORKDIR /code/app
CMD ["python3", "main.py"]