services:
  Webserver:
    image: rtsp/lighttpd
    container_name: lighttpd
    ports:
      - "80:80"
    volumes:
      - /home/pi/Project/Project_Pool_VC01/html:/var/www/html:ro
    restart: unless-stopped
    depends_on:
      - mariadb
      - fastapi

  fastapi:
    build: api
    container_name: fastapi
    environment:
      TZ: "Europe/Brussels"
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: pool_monitor_vc01
      HOST: mariadb
      PORT: 3306
      REMINDER_APP_PASSWORD: "oawc kpys kjbq rwre"
      REMINDER_EMAIL: "zwembad.VC01@gmail.com"
    ports:
      - "8000:8000"
    volumes:
      - /home/pi/Project/Project_Pool_VC01/api/main.py:/code/app/main.py:ro
      - /home/pi/Project_Logs:/code/app/logfile.log
    restart: unless-stopped
    depends_on:
      - mariadb

  message:
    build: message_shedule
    container_name: message
    environment:
      URL: "http://fastapi:8000"
    volumes:
      - /home/pi/Project/Project_Pool_VC01/message_shedule/message.py:/code/app/main.py:ro
    restart: unless-stopped
    depends_on:
      - fastapi
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pool_monitor_vc01
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
    volumes:
      - /home/pi/DB_data:/var/lib/mysql  # Bind mount for database files
      - /home/pi/project/Project_Pool_VC01/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Initial SQL script
    ports:
      - "3306:3306"
    restart: unless-stopped
